name: TT
channels:
  - tmip
  - plotly
  - conda-forge
  - defaults
  - jpn
  
dependencies:
  - python=3.7
  - pip

  # Security
  - defaults::openssl
  - defaults::certifi
  - defaults::ca-certificates
  
  # Math
  - defaults::numpy>=1.16
  - defaults::numpy-base
  - defaults::mkl
  - defaults::mkl_fft
  - defaults::mkl_random
  - defaults::blas
  - defaults::intel-openmp
  - defaults::pandas>=0.23.4
  - defaults::scipy>=1.2
  - jpn::ghalton>=0.6.1
  
  # Networks
  - networkx>=2.2
  
  # YAML Processing
  - jpn::yamllint>=1.11
  - jpn::pathspec>=0.5.9
  
  # Data Storage and File Management
  - pytables=3.4.4
  - h5py>=2.8.0
  - hdf5>=1.10.2
  - appdirs>=1.4.3
  
  # Visualization
  - matplotlib>=3.0.1
  - seaborn>=0.9
  - pydot
  - graphviz>=2.38
  - plotly>=4.1
  - plotly::plotly-orca  # Plotly Static Image Export
  
  # Mapping
  - conda-forge::fiona>=1.7.11
  - conda-forge::gdal>=2.2.4
  - conda-forge::geopandas>=0.4
  - conda-forge::krb5>=1.16
  - conda-forge::shapely>=1.6.4
  - conda-forge::osmnx>=0.9
  - conda-forge::contextily
  - conda-forge::libiconv
  - conda-forge::fontconfig
  - jpn::mapped
  
  # User Interface
  - ipywidgets>=7.2
  
  # Parallel Processing
  - joblib>=0.13.2
  - cloudpickle>=0.6.1
  
  # MS Excel Compatibility
  - openpyxl>=2.4
  - xlrd
  
  # HTML Compatibility
  - beautifulsoup4>=4.6
  - jinja2>=2.9.6  # for pandas styler
  - jpn::xmle
  - html5lib
  
  # Jupyter and IPython
  - ipykernel>=5.1
  - nb_conda>=2.2.1
  - jupyterlab>=1.0.4
  - jupyterlab_server>=1.0.0
  - notebook>=5.7.2
  - conda-forge::nodejs
  - conda-forge::jupyter_contrib_nbextensions>=0.4.0   # on conda-forge only
  - conda-forge::jupytext

  
  # Choice Modeling
  - jpn::filez
  - jpn::addict_yaml
  - jpn::larch>=5.1
  
  # Testing
  - pytest>=4.0.1
  
  - pip:
      - transportation_tutorials
  
